export const TRACKS = [
  {
    id: 4,
    name: 'Loop Holes',
    description: "Bleep-bleep-boop, Subject's favourite",
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-loopholes.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/tracks%20thumbnails/loopholes.jpg',
    list: 'Tracks',
  },
  {
    id: 2,
    name: 'Broken Bottles',
    description: 'A rowdy anthem for people who want to break stuff',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-brokenbottles.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/tracks%20thumbnails/brokenbottles.jpg',
    list: 'Tracks',
  },
  {
    id: 1,
    name: 'Super Hyphy RMX',
    description: "Let's get dumb",
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-superhyphyrmx.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/tracks%20thumbnails/superhyphyrmx.jpg',
    list: 'Tracks',
  },
  {
    id: 3,
    name: 'Hells Bells',
    description: 'Dark, gloomy, built to break down',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-hellsbells.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/tracks%20thumbnails/hellsbells.jpg',
    list: 'Tracks',
  },
  {
    id: 5,
    name: '1984',
    description: 'Block Control theme',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-1984',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/tracks%20thumbnails/1984.jpg',
    list: 'Tracks',
  },
  {
    id: 6,
    name: 'Paper Cuts',
    description: 'Breaks and breaks only',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-papercuts.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/tracks%20thumbnails/papercuts.jpg',
    list: 'Tracks',
  },
  {
    id: 7,
    name: 'DJ Demo 01',
    description: 'Bassy beats, Techno and more. Last known entry',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-last-entry.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/mixes%20thumbnails/lastentry.jpg',
    list: 'Mixes',
  },
  {
    id: 8,
    name: 'DJ Demo 02',
    description: 'Techno and gets a bit dark',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-notfound.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/mixes%20thumbnails/unknown.jpg',
    list: 'Mixes',
  },
  {
    id: 9,
    name: 'DJ Demo 03',
    description: 'Rap, funky and half time on Knife and Fork Radio',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-live-on-knifeandfork-radio.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/mixes%20thumbnails/knifeandfork.jpg',
    list: 'Mixes',
  },
  {
    id: 10,
    name: 'DJ Demo 04',
    description: 'Techno for the Conkrete MTL family',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-for-conkrete-mtl.mp3',
    thumbnail: 'https://storage.googleapis.com/blockcontrol-2026/mixes%20thumbnails/concrete.jpg',
    list: 'Mixes',
  },
];
