export const TRACKS = [
  {
    id: 1,
    name: 'Super Hyphy RMX',
    description: "Let's get dumb",
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-superhyphyrmx.mp3',
    list: 'Tracks',
  },
  {
    id: 2,
    name: 'Broken Bottles',
    description: 'A rowdy anthem for people who want to break stuff',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-brokenbottles.mp3',
    list: 'Tracks',
  },
  {
    id: 3,
    name: 'Hells Bells',
    description: 'Dark, gloomy, built to break down',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-hellsbells.mp3',
    list: 'Tracks',
  },
  {
    id: 4,
    name: 'Loop Holes',
    description: "Bleep-bleep-boop, vocal cuts and a classic sample — subject's favourite",
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-loopholes.mp3',
    list: 'Tracks',
  },
  {
    id: 5,
    name: '1984',
    description: 'Blackout theme for the last ones left',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-1984',
    list: 'Tracks',
  },
  {
    id: 6,
    name: 'Paper Cuts',
    description: 'Breaks and breaks only',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-papercuts.mp3',
    list: 'Tracks',
  },
  {
    id: 7,
    name: 'DJ Demo 01',
    description: 'Last known entry — Techno',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-last-entry.mp3',
    list: 'Mixes',
  },
  {
    id: 8,
    name: 'DJ Demo 02',
    description: 'Not Found — Techno',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-notfound.mp3',
    list: 'Mixes',
  },
  {
    id: 9,
    name: 'DJ Demo 03',
    description: 'Rap, funky and half time — live on Nasty.FM w/ Knife and Fork Radio',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-live-on-knifeandfork-radio.mp3',
    list: 'Mixes',
  },
  {
    id: 10,
    name: 'DJ Demo 04',
    description: 'Special guest techno mix for the Conkrete MTL family',
    src: 'https://storage.googleapis.com/blockcontrol-2026/blockcontrol-djdemo-for-conkrete-mtl.mp3',
    list: 'Mixes',
  },
];
